_monk_post_guard_hello = ["meet_monk_idap_hello_1","meet_monk_idap_hello_2","meet_monk_idap_hello_3"];
_monk_post_guard_hello_sleep = [0.4,1,1.8];
_rndphrase = _monk_post_guard_hello call BIS_fnc_selectRandom;
_getsleepInd = _monk_post_guard_hello find _rndphrase;
_getsleep = _monk_post_guard_hello_sleep select _getsleepInd;
	civ_monk_idap setRandomLip true;
	civ_monk_idap say3D _rndphrase; 
	sleep _getsleep;
	civ_monk_idap setRandomLip false;
	// [monk_post_guard_1, (_monk_post_guard_hello select floor random count _monk_post_guard_hello)] call CBA_fnc_globalSay3d;
	sleep 10;